apiVersion: apps/v1
kind: Deployment
metadata:
  name: aibilling
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aibilling
  template:
    metadata:
      labels:
        app: aibilling
    spec:
      containers:
      - name: aibilling
        image: asia-east1-docker.pkg.dev/ann-project-390401/ann-repo/aibilling:latest
        imagePullPolicy: Always
        env:
        - name: APP_ENV
          valueFrom:
            secretKeyRef:
              name: ann-secret
              key: APP_ENV
        - name: PROJECT_ID
          valueFrom:
            secretKeyRef:
              name: ann-secret
              key: PROJECT_ID
        - name: REGION
          value: "asia-east1"
        - name: DB_NAME
          value: "ann"
        - name: DB_USERNAME
          value: "postgres"
        - name: DB_PASSWORD
          value: "Lqo|L)$dG|PDB?Z-"
        - name: DB_PORT
          value: "5433"
        - name: DB_HOST
          value: "127.0.0.1"
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: "2Gi"
            cpu: "500m"
          requests:
            memory: "1Gi"
            cpu: "250m"