"""add gcp bill

Revision ID: 1afbc900e6d8
Revises: 9ca6b9af842e
Create Date: 2024-03-31 09:40:02.730976

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1afbc900e6d8'
down_revision = '9ca6b9af842e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gcp_bill',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('account_name', sa.String(length=100), nullable=True),
    sa.Column('account_id', sa.String(length=100), nullable=True),
    sa.Column('project_name', sa.String(length=100), nullable=True),
    sa.Column('project_id', sa.String(length=100), nullable=True),
    sa.Column('project_number', sa.BigInteger(), nullable=True),
    sa.Column('service_name', sa.String(length=100), nullable=True),
    sa.Column('service_id', sa.String(length=100), nullable=True),
    sa.Column('service_sku', sa.TEXT(), nullable=True),
    sa.Column('sku_id', sa.String(length=50), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('amount', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('amount_unit', sa.String(length=50), nullable=True),
    sa.Column('detail_fee', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('price', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('unrounded_fee', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('rounded_fee', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_gcp_bill'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('gcp_bill')
    # ### end Alembic commands ###
